spring.datasource.url=jdbc:mysql://db:3306/docker?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=shefoo
spring.datasource.password=shefoo

# Redis server host and port
spring.data.redis.host=redis
spring.data.redis.port=6379
